# Generated by Django 2.2.7 on 2019-12-09 13:56

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0002_follower_pitt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
